autolabeler:
  - label: 'skip-changelog'
    branch:
      - '/^dependabot\/.+'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
  - label: 'enhancement'
    branch:
      - '/enhancement\/.+/'
  - label: 'chore'
    branch:
      - '/chore\/.+/'

categories:
  - title: '🚀 Enhancements'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'

change-template: '- #$NUMBER $TITLE (@$AUTHOR)'

exclude-labels:
  - 'skip-changelog'

name-template: 'v$RESOLVED_VERSION'

replacers:
  # Exclude dependabot[bot] from contributor list.
  - search: '/(?:\s+and\s+)?@dependabot\[bot\](?:,?\s+)/g'
    replace: ''

tag-template: 'v$RESOLVED_VERSION'

template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
