autolabeler:
  - label: 'bug'
    branch:
      - '/fix\/.+/'
  - label: 'enhancement'
    branch:
      - '/enhancement\/.+/'
  - label: 'chore'
    branch:
      - '/chore\/.+/'

categories:
  - title: '🚀 Enhancements'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '🛠 Dependency Updates'
    label: 'dependencies'

change-template: '- #$NUMBER $TITLE (@$AUTHOR)'

exclude-labels:
  - 'skip-changelog'

name-template: 'v$RESOLVED_VERSION'

tag-template: 'v$RESOLVED_VERSION'

template: |
  <!-- WARNING: Any changes made here will be lost when a new commit is pushed to the default branch. -->
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
