name: Automerge

on:
  # ⚠️ WARNING: Secrets can be accessed by forks when triggered via this event!
  # In this case no code is checked out and no cache is being saved, so this workflow should be fine.
  # See https://securitylab.github.com/research/github-actions-preventing-pwn-requests/.
  pull_request_target:
    types: [opened, reopened]

jobs:
  automerge-dependencies:
    name: Automerge dependencies
    runs-on: ubuntu-latest
    if: >
      github.actor == 'dependabot[bot]' &&
      github.event.pull_request.auto_merge == null
    steps:
      - name: Enable auto-merge for the PR
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.AUTOMERGE_TOKEN }}
